### ISSUE TITLE
Create local/mounted file system cloning

### ISSUE THREAD

**Issue by mpacer** [nteract/bookstore#110]
A use case has come up where it would be helpful for bookstore to be able to clone from a network attached file system. 

Given @MSeal's other comments about the need for us to eventually generalize bookstore functionality beyond AWS services in line with `papermill` and other applications (which have compatibility with e.g., Azure). This may be a good test case for building that abstraction from an API perspective.

**Comment by rgbkrk** [comment]
Might want to label this local storage cloning, since it tends not to make a difference what the underlying filesystem is. It's mostly just about pointing to the right file mount location.

**Comment by mpacer** [comment]
That's a good point!

**Comment by mpacer** [comment]
Closing in favour of #154
