### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by willingc** [nteract/bookstore#118]
PR #117 adds display of test coverage as a badge in the README, on every Python 3.6 travis run and on local test runs using tox.

Let's work on increasing coverage on these files (in priority order):

- [x] `archive.py`
- [x] `publish.py`
- [x] `handlers.py`
- [x] `clone.py`
- [x] `utils.py`

This will get us closer to our release benchmark in #96.

**Comment by willingc** [comment]
#127 adds tests to reach 100% file coverage of s3_paths.py

**Comment by willingc** [comment]
#128 adds a few tests for archive and a test stub file for publish.

@mpacer @MSeal @rgbkrk After these land we should be at approx 49% coverage.

**Comment by willingc** [comment]
Now @mpacer's latest PR pushes us to high 60s. Woo! 👍

**Comment by mpacer** [comment]
We landed on 79% by the time of release — it feels pretty darn good.

Closing!
