### ISSUE TITLE
Python API docs are broken/redundant

### ISSUE THREAD

**Issue by mpacer** [nteract/bookstore#122]
Right now the readthedocs doesn't show any autodoc documentation being built for the Python API: 
![image](https://user-images.githubusercontent.com/2482408/59134461-23965100-8930-11e9-8683-b6258c5f6714.png)

This is a fairly straightforward RST issue (number of underscore characters underneathe one of the rst header names in the store_client.rst).

But in addition, it looks like the methods for the handlers are being displayed twice, once from the class docstring's `Methods` section, once from each of the method's functional docstrings. The latter do not include the self parameter:
![image](https://user-images.githubusercontent.com/2482408/59134575-7ff97080-8930-11e9-8505-a408d3f63298.png)

@willingc What is the right way to go here to make the documentation make sense (ignoring the lack of the docs build which I'll fix with a small PR shortly).

**Comment by willingc** [comment]
#123 (Thank you) fixed a problem. There is something up with the RTD build and the latest Sphinx changes and RTD.

I think the duplication is coming from the Class Docstring being followed closely by the method docstrings. We likely need to add some distinction either via css or headings.

**Comment by willingc** [comment]
#124 fixed the build configuration. Working on polishing the docs in a separate PR.

**Comment by willingc** [comment]
Hi @mpacer. I merged two PRs cleaning up the doc build and the formatting. I've added some additional headings on the autodoc pages. Please take a [look](https://bookstore.readthedocs.io/en/latest/reference/index.html). If you have any desired changes, either leave a note here, edit directly, or open a PR. Thanks!

**Comment by willingc** [comment]
Going to close this @mpacer since I think this is resolved.
