### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by mjbeyeler** [nteract/bookstore#144]
Hello!

As someone who is concerned about reproducibility I was wondering if a Conda package for bookstore is being developed (or already exists and i just didn't happen to find it).

Best

**Comment by willingc** [comment]
@mjbeyeler We will be releasing a package on conda forge soon. :sunny:

**Comment by willingc** [comment]
A PR has been submitted to conda-forge's staged-recipes https://github.com/conda-forge/staged-recipes/pull/8728

**Comment by willingc** [comment]
@mjbeyeler The conda-forge package has been released. See https://github.com/conda-forge/bookstore-feedstock
