### ISSUE TITLE
how to publish

### ISSUE THREAD

**Issue by taniki** [nteract/bookstore#57]
Hi,

I have installed and set up bookstore but I am not sure about how notebooks are supposed to be copied from the `workspace` to the `published`. On save notebooks seem to gracefully be stored on S3 but can't find how to properly publish then.

**Comment by rgbkrk** [comment]
Hi @taniki! We're currently working on UI for this in the nteract frontend with https://github.com/nteract/nteract/pull/4144 and https://github.com/nteract/nteract/pull/4122. As of today you'd have to perform a `PUT` against the `/api/bookstore/published` endpoint directly: https://github.com/nteract/bookstore/blob/master/bookstore/handlers.py#L89

**Comment by taniki** [comment]
ok that's great. I will wait for the feature be shipped in a next nteract release then :smile:
