### ISSUE TITLE
Create a plan for release 2.3

### ISSUE THREAD

**Issue by willingc** [nteract/bookstore#61]
What features or changes should we target for release 2.3.0?

**Comment by rgbkrk** [comment]
* [ ] Cloning endpoint #63
* [ ] UI for cloning #64

**Comment by willingc** [comment]
Thanks @rgbkrk. I've created a `2.3 Release` milestone and have tagged these two items. From here, let's close this and use the milestone to keep track of the next release content.

**Comment by rgbkrk** [comment]
Perfect!
